accounts/urls.py
from django.urls import path, include

from . import views

app_name = "accounts"
urlpatterns = [
    # Include deafault auth urls
    path("", include("django.contrib.auth.urls")),
    # registration page
    path("register/", views.register, name="register"),
]

blog_app/urls.py
from django.urls import path

from . import views

app_name = "blog_app"

urlpatterns = [
    # home page
    path("", views.index, name="index"),
    # add new post
    path("add_post/", views.add_post, name="add_post"),
    # page that shows all user's posts
    path("user_posts/", views.user_posts, name="user_posts"),
    # edit post
    path("edit_post/<int:post_id>/", views.edit_post, name="edit_post"),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("blog_app.urls")),
]

accounts/models.py
from django.db import models

# Create your models here.

blog_app/models.py
from django.db import models
from django.contrib.auth.models import User


class PostCategory(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Post Categories"

    def __str__(self):
        return self.name


class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(PostCategory, on_delete=models.SET_NULL, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        BlogPost, on_delete=models.CASCADE, related_name="comments"
    )
    name = models.CharField(max_length=100)
    email = models.EmailField()
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.post.title} - {self.name}"

blog_app/forms.py
from django import forms

from .models import BlogPost


class PostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ["title", "content", "category"]
        labels = {"title": "", "content": "", "category": ""}
        widgets = {"content": forms.Textarea(attrs={"cols": 80})}

    # so that the category field is not required - from StackOverflow
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields["category"].required = False

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# register a new user
def register(request):
    if request.method != "POST":
        # Display blank registration form
        form = UserCreationForm()
    else:
        # process completed form
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # log in the user and then redirect to home page
            login(request, new_user)
            return redirect("blog_app:index")
    # Display a blank or invalid form.
    context = {"form": form}
    return render(request, "registration/register.html", context)

blog_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.


from django.urls import path
from .models import BlogPost, PostCategory, Comment
from django.http import HttpResponse

from .forms import PostForm


def index(request):
    posts = BlogPost.objects.order_by("-date_posted")
    context = {"posts": posts}
    # return HttpResponse("Hello, world. You're at the Blog main page.")
    return render(request, "blog_app/index.html", context)


@login_required
def add_post(request):
    if request.method != "POST":
        # no data submitted; create blank form
        form = PostForm()
    else:
        # POST data submitted; process data
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect("blog_app:index")
    context = {"form": form}
    return render(request, "blog_app/add_post.html", context)


@login_required
def user_posts(request):
    posts = BlogPost.objects.filter(owner=request.user).order_by("-date_posted")
    context = {"posts": posts}
    return render(request, "blog_app/user_posts.html", context)


@login_required
def edit_post(request, post_id):
    post = BlogPost.objects.get(id=post_id)
    if post.owner != request.user:
        raise Http404
    if request.method != "POST":
        # initial request; pre-fill form with current post
        form = PostForm(instance=post)
    else:
        # POST data submitted; process data
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("blog_app:user_posts")

    context = {"post": post, "form": form}
    return render(request, "blog_app/edit_post.html", context)

blog_app/templates/blog_app/add_post.html
{% extends "blog_app/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2>Add a new post</h2>
{% endblock page_header %}

{% block content %}
  <form action="{% url 'blog_app:add_post' %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    {% bootstrap_form form %}
    {% bootstrap_button button_type='submit' content='register'%}
  </form>

{% endblock content %}

blog_app/templates/blog_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Blog</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4 border">
        <div class="container-fluid px-3">
          <a class="navbar-brand" href="{% url 'blog_app:index' %}">Blog app</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog_app:index' %}">Home</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class='nav-link' href="{% url 'blog_app:user_posts' %}">Your posts</a>
              </li>
              <li class="nav-item">
                <a class='nav=link' href="{% url 'blog_app:add_post' %}">Create new post</a>
              </li>
              <li class="nav-item">
                <form action="{% url 'accounts:logout' %}" method='post'>
                    {% csrf_token %}
                    <button name='logout'>Log out</button>
                </form>
              </li>
              {% else %}
              <li class="nav-item"><a class='nav-link' href="{% url 'accounts:login' %}">Log in</a></li>
              <li class="nav-item"><a class='nav-link' href="{% url 'accounts:register' %}">Register</a></li> 
            {% endif %}
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success disabled" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      <main class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %} {% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
      </main>
</body>
</html>

blog_app/templates/blog_app/edit_post.html
{% extends "blog_app/base.html" %}

{% block content %}
  <p>Edit existing post:</p>
  <form action="{% url 'blog_app:edit_post' post.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Edit post</button>
  </form>

{% endblock content %}

blog_app/templates/blog_app/index.html
{% extends 'blog_app/base.html' %}
{% block page_header %}
    <div class="p-3 mb-3 bg-light border rounded-3">
        <div class="container-fluid py4 text-center">
            <h1 class="display-3">
                My Blog, Heck Yeah! Or maybe our blog?
            </h1>
        </div>
    </div>
{% endblock page_header %}
{% block content %}
<h1 class='p-3'>Logged in?</h1>
<div class="d-flex justify-content-center p-2">
    {% if user.is_authenticated %}
        Hello, {{ user.username }}.
    {% else %}
        <a href="{% url 'accounts:login' %}" class="btn btn-primary btn-lg mt-1">Log in </a>
        <h1 class='mx-4'> or </h1>
        <a href="{% url 'accounts:register' %}" class="btn btn-primary btn-lg mt-1"> Register</a>
    {% endif %}
</div>

<div class="posts">
    <h1 class='mt-3'>All blog posts</h1>
    {% for post in posts %}
    <div class="card my-4">
        <div class="card-header">
            <h2>
                {{ post.title }}
            </h2>
            <small> {{ post.date_posted }} </small>
        </div>
        <div class="card-body">
            <p> {{ post.content }} </p>
        </div>
        <div class="card-footer d-flex justify-content-around">
            <p> Author: {{ post.owner }} </p>
            <p> Category: {{ post.category }} </p>
        </div>
    </div>

    {% endfor %}

</div>

{% endblock content %}

blog_app/templates/blog_app/user_posts.html
{% extends 'blog_app/base.html' %}
{% block content %}

<p>Your posts</p>

  <ul>
    {% for post in posts %}
    <h3> {{ post.title }} </h3>
        <p> {{ post.content }} </p>
        <p> {{ post.date_posted }} </p>
        <p> Category: {{ post.category }} </p>
        <p> Author: {{ post.owner }} </p>
        <a href="{%  url 'blog_app:edit_post' post.id %}" >Edit post</a>
        <br />
    {% endfor %}
  </ul>


{% endblock content %}